spring:
  kafka:
    bootstrap-servers: 여기에카프카엔드포인트
  datasource:
    url: jdbc:mariadb://여기에디비엔드포인트:3306/social_todo_backend
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
