spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/jpa_test
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
